//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johnny.CMS.admin.seh {
    
    
    public partial class bestpracticeadd {
        
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litPageTitle;
        
        /// <summary>
        /// litBestPracticeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litBestPracticeName;
        
        /// <summary>
        /// txtBestPracticeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.TextBox.TextBox txtBestPracticeName;
        
        /// <summary>
        /// txtBestPracticeNameTip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel txtBestPracticeNameTip;
        
        /// <summary>
        /// litShortDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litShortDescription;
        
        /// <summary>
        /// txtShortDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.TextBox.TextBox txtShortDescription;
        
        /// <summary>
        /// txtShortDescriptionTip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel txtShortDescriptionTip;
        
        /// <summary>
        /// litContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litContent;
        
        /// <summary>
        /// fckContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FredCK.FCKeditorV2.FCKeditor fckContent;
        
        /// <summary>
        /// litHits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litHits;
        
        /// <summary>
        /// txtHits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.TextBox.TextBox txtHits;
        
        /// <summary>
        /// txtHitsTip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel txtHitsTip;
        
        /// <summary>
        /// litIsDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litIsDisplay;
        
        /// <summary>
        /// rdbDisplay0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Button.ValidationRadioButton rdbDisplay0;
        
        /// <summary>
        /// rdbDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Button.ValidationRadioButton rdbDisplay1;
        
        /// <summary>
        /// rdbDisplay0Tip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel rdbDisplay0Tip;
        
        /// <summary>
        /// litRdbDisplayTip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRdbDisplayTip;
        
        /// <summary>
        /// litCreatedTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litCreatedTime;
        
        /// <summary>
        /// lblCreatedTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCreatedTime;
        
        /// <summary>
        /// litCreatedByName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litCreatedByName;
        
        /// <summary>
        /// lblCreatedByName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCreatedByName;
        
        /// <summary>
        /// litUpdatedTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litUpdatedTime;
        
        /// <summary>
        /// lblUpdatedTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUpdatedTime;
        
        /// <summary>
        /// litUpdatedByName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Literal.Literal litUpdatedByName;
        
        /// <summary>
        /// lblUpdatedByName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUpdatedByName;
        
        /// <summary>
        /// btnAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Button.Button btnAdd;
        
        /// <summary>
        /// btnReset control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Johnny.Controls.Web.Button.ResetButton btnReset;
    }
}
