//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johnny.Controls.Web.Assembly_Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlTexts_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlTexts_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Johnny.Controls.Web.Assembly_Resx.ControlTexts_zh", typeof(ControlTexts_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确定要重置该用户的密码吗？.
        /// </summary>
        public static string Button_ResetConfirmation {
            get {
                return ResourceManager.GetString("Button_ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置密码.
        /// </summary>
        public static string Button_ResetPassword {
            get {
                return ResourceManager.GetString("Button_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保 存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总记录:{2},&amp;nbsp;&amp;nbsp;页次:{0}/{1}页,&amp;nbsp;&amp;nbsp;{3}/页.
        /// </summary>
        public static string ManageGridView_CurrentPage {
            get {
                return ResourceManager.GetString("ManageGridView_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string ManageGridView_Delete {
            get {
                return ResourceManager.GetString("ManageGridView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定删除[{0}]吗？.
        /// </summary>
        public static string ManageGridView_DeleteConfirmation {
            get {
                return ResourceManager.GetString("ManageGridView_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  首页 .
        /// </summary>
        public static string ManageGridView_FirstPage {
            get {
                return ResourceManager.GetString("ManageGridView_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  转到此页 .
        /// </summary>
        public static string ManageGridView_GoPage {
            get {
                return ResourceManager.GetString("ManageGridView_GoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  尾页 .
        /// </summary>
        public static string ManageGridView_LastPage {
            get {
                return ResourceManager.GetString("ManageGridView_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        public static string ManageGridView_Modify {
            get {
                return ResourceManager.GetString("ManageGridView_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下移.
        /// </summary>
        public static string ManageGridView_MoveDown {
            get {
                return ResourceManager.GetString("ManageGridView_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上移.
        /// </summary>
        public static string ManageGridView_MoveUp {
            get {
                return ResourceManager.GetString("ManageGridView_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  下页 .
        /// </summary>
        public static string ManageGridView_NextPage {
            get {
                return ResourceManager.GetString("ManageGridView_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string ManageGridView_Operation {
            get {
                return ResourceManager.GetString("ManageGridView_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  上页 .
        /// </summary>
        public static string ManageGridView_PreviousPage {
            get {
                return ResourceManager.GetString("ManageGridView_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重 置.
        /// </summary>
        public static string ResetButton_Reset {
            get {
                return ResourceManager.GetString("ResetButton_Reset", resourceCulture);
            }
        }
    }
}
